name: C/C++ CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        target: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.target }}

    steps:
    - uses: actions/checkout@v6
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make coverage
      run: make coverage
    - name: make docs
      if: ${{ matrix.target == 'ubuntu-latest' }}
      run: |
        sudo apt update
        sudo apt install doxygen
        make docs
